### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by chenvan** [lalalic/docx4js#20]
Recently, I upgraded doxc4js from 3.1.1. But it showed 'ReferenceError: URL is not defined' when I ran my program.

```js
error occur in addOPLToEs:  ReferenceError: URL is not defined
    at _class.getDataPartAsUrl (/root/parseOPL/node_modules/docx4js/lib/document.js:74:37)
    at OfficeDocument.getRel (/root/parseOPL/node_modules/docx4js/lib/openxml/part.js:77:25)
    at Object.pic (/root/parseOPL/node_modules/docx4js/lib/openxml/docx/officeDocument.js:206:55)
    at identify (/root/parseOPL/node_modules/docx4js/lib/openxml/docx/officeDocument.js:94:48)
    at OfficeDocument.renderNode (/root/parseOPL/node_modules/docx4js/lib/openxml/part.js:193:17)
    at /root/parseOPL/node_modules/docx4js/lib/openxml/part.js:215:23
    at Array.map (<anonymous>)
    at OfficeDocument.renderNode (/root/parseOPL/node_modules/docx4js/lib/openxml/part.js:214:30)
    at /root/parseOPL/node_modules/docx4js/lib/openxml/part.js:215:23
    at Array.map (<anonymous>)
    at OfficeDocument.renderNode (/root/parseOPL/node_modules/docx4js/lib/openxml/part.js:214:30)
    at /root/parseOPL/node_modules/docx4js/lib/openxml/part.js:215:23
    at Array.map (<anonymous>)
    at OfficeDocument.renderNode (/root/parseOPL/node_modules/docx4js/lib/openxml/part.js:214:30)
    at /root/parseOPL/node_modules/docx4js/lib/openxml/part.js:215:23
    at Array.map (<anonymous>)
```

**Comment by magnetnation** [comment]
Any plans on fixing this?
In the readme it clearly states that node.js is supported platform.

**Comment by lalalic** [comment]
I'll check it later. the solution is to implement URL object on global.
