### ISSUE TITLE
Old version in npm

### ISSUE THREAD

**Issue by atnartur** [lalalic/docx4js#5]
When I do `npm i docx4js` and start the app I see the error `not found xmldom module`. In package.json in git repository this module included. But in npm registry this module not found in package.json.
Updating module in npm can fix this problem

**Comment by SHocker-Yu** [comment]
Hi,did you use the example successfully?
I have a problem like this:
F:\parseWord\docx4js.js:18
            return DOCX.createVisitorFactory(function(wordModel){
            ^^^^^^

SyntaxError: Unexpected token return
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by atnartur** [comment]
@SHocker-Yu you should create another issue for your bug or problem. And can you attach some lines before the line with bug in new issue?

**Comment by lalalic** [comment]
fixed manually
