### ISSUE TITLE
upload .docx file error: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by En777** [lalalic/docx4js#69]
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at _class._init (officeDocument.js:16:16)
    at _class._init (officeDocument.js:6:3)
    at _class.Part (part.js:31:8)
    at _class (officeDocument.js:2:1)
    at new _class (officeDocument.js:2:1)
    at _class (document.js:9:23)
    at new _class (document.js:2:1)
    at parse (document.js:177:14)
    at reader.onload (document.js:194:6)

**Comment by En777** [comment]
same error as https://github.com/VolodymyrBaydalka/docxjs/issues/58

I fix it at my fork , maybe it not best
https://github.com/En777/docxjs-word-preview/commit/9eed2dbb212de225c60dd619c69cb4ea70377780

and my npm package
https://www.npmjs.com/package/docx-preview-lib
